In [56]:
import pandas as pd
from sqlalchemy import create_engine, inspect

### Extract CSVs into DataFrames

In [57]:
women_shoe_file = "../Resources/7003_1.csv"
women_shoe_df = pd.read_csv(women_shoe_file)
women_shoe_df.head()

/var/folders/_3/fpx1kffx6n90zjt7rjys0h6r0000gn/T/ipykernel_15738/2213068837.py:2: DtypeWarning: Columns (25,36,39,44) have mixed types. Specify dtype option on import or set low_memory=False.
  women_shoe_df = pd.read_csv(women_shoe_file)

,id,asins,brand,categories,colors,count,dateadded,dateupdated,descriptions,dimension,...,prices_sourceurls,prices_warranty,quantities,reviews,sizes,skus,sourceurls,upc,websiteids,weight
0,AVpfBXx21cnluZ0-cKxs,NaN,Zoot,"Shoes,Clothing,Women's Shoes,All Women's Shoes","Blue,Multicolor",NaN,2016-11-11T09:49:00Z,2016-11-11T09:49:00Z,"[{""dateSeen"":[""2016-11-11T09:49:00Z""],""sourceU...",NaN,...,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN,"10,9",NaN,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN
1,AVpfBXx21cnluZ0-cKxs,NaN,Zoot,"Shoes,Clothing,Women's Shoes,All Women's Shoes","Blue,Multicolor",NaN,2016-11-11T09:49:00Z,2016-11-11T09:49:00Z,"[{""dateSeen"":[""2016-11-11T09:49:00Z""],""sourceU...",NaN,...,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN,"10,9",NaN,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN
2,AVpfBXx21cnluZ0-cKxs,NaN,Zoot,"Shoes,Clothing,Women's Shoes,All Women's Shoes","Blue,Multicolor",NaN,2016-11-11T09:49:00Z,2016-11-11T09:49:00Z,"[{""dateSeen"":[""2016-11-11T09:49:00Z""],""sourceU...",NaN,...,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN,"10,9",NaN,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN
3,AVpfBXx21cnluZ0-cKxs,NaN,Zoot,"Shoes,Clothing,Women's Shoes,All Women's Shoes","Blue,Multicolor",NaN,2016-11-11T09:49:00Z,2016-11-11T09:49:00Z,"[{""dateSeen"":[""2016-11-11T09:49:00Z""],""sourceU...",NaN,...,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN,"10,9",NaN,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN
4,AVpfEqFRLJeJML431x7w,NaN,Wild Pair,"Shoes,Women's Shoes,Clothing,All Women's Shoes",Brown,NaN,2016-11-16T12:56:36Z,2016-11-16T12:56:36Z,"[{""dateSeen"":[""2016-11-16T12:56:36Z""],""sourceU...",NaN,...,https://www.walmart.com/ip/Wild-Pair-Colfax-Wo...,NaN,NaN,NaN,"8.5,7,7.5,8",NaN,https://www.walmart.com/ip/Wild-Pair-Colfax-Wo...,7.63181E+11,NaN,NaN

In [58]:
men_shoe_file = "../Resources/7004_1.csv"
men_shoe_df = pd.read_csv(men_shoe_file)
men_shoe_df.head()

/var/folders/_3/fpx1kffx6n90zjt7rjys0h6r0000gn/T/ipykernel_15738/380449232.py:2: DtypeWarning: Columns (39,45) have mixed types. Specify dtype option on import or set low_memory=False.
  men_shoe_df = pd.read_csv(men_shoe_file)

,id,asins,brand,categories,colors,count,dateadded,dateupdated,descriptions,dimension,...,prices_warranty,quantities,reviews,sizes,skus,sourceurls,upc,vin,websiteids,weight
0,AVpfHrJ6ilAPnD_xVXOI,NaN,Josmo,"Clothing,Shoes,Men's Shoes,All Men's Shoes",NaN,NaN,2016-11-07T00:45:12Z,2016-11-07T00:45:12Z,"[{""dateSeen"":[""2016-11-07T00:45:12Z""],""sourceU...",NaN,...,NaN,NaN,NaN,NaN,NaN,https://www.walmart.com/ip/Josmo-8190-Plain-In...,699302044036,NaN,NaN,NaN
1,AVpfHrJ6ilAPnD_xVXOI,NaN,Josmo,"Clothing,Shoes,Men's Shoes,All Men's Shoes",NaN,NaN,2016-11-07T00:45:12Z,2016-11-07T00:45:12Z,"[{""dateSeen"":[""2016-11-07T00:45:12Z""],""sourceU...",NaN,...,NaN,NaN,NaN,NaN,NaN,https://www.walmart.com/ip/Josmo-8190-Plain-In...,699302044036,NaN,NaN,NaN
2,AVpfHsWP1cnluZ0-eVZ7,NaN,SERVUS BY HONEYWELL,"All Men's Shoes,Shoes,Men's Shoes,Clothing",NaN,NaN,2016-06-14T04:29:57Z,2016-07-09T20:26:48Z,"[{""dateSeen"":[""2016-07-09T20:26:48Z""],""sourceU...",NaN,...,NaN,NaN,NaN,NaN,NaN,http://www.walmart.com/ip/Studs-Shoe-Large-Pr-...,NaN,NaN,NaN,NaN
3,AVpfHsWP1cnluZ0-eVZ7,NaN,SERVUS BY HONEYWELL,"All Men's Shoes,Shoes,Men's Shoes,Clothing",NaN,NaN,2016-06-14T04:29:57Z,2016-07-09T20:26:48Z,"[{""dateSeen"":[""2016-07-09T20:26:48Z""],""sourceU...",NaN,...,NaN,NaN,NaN,NaN,NaN,http://www.walmart.com/ip/Studs-Shoe-Large-Pr-...,NaN,NaN,NaN,NaN
4,AVpfHsWP1cnluZ0-eVZ7,NaN,SERVUS BY HONEYWELL,"All Men's Shoes,Shoes,Men's Shoes,Clothing",NaN,NaN,2016-06-14T04:29:57Z,2016-07-09T20:26:48Z,"[{""dateSeen"":[""2016-07-09T20:26:48Z""],""sourceU...",NaN,...,NaN,NaN,NaN,NaN,NaN,http://www.walmart.com/ip/Studs-Shoe-Large-Pr-...,NaN,NaN,NaN,NaN

In [70]:
women_shoe_df["categories"]

0           Shoes,Clothing,Women's Shoes,All Women's Shoes
1           Shoes,Clothing,Women's Shoes,All Women's Shoes
2           Shoes,Clothing,Women's Shoes,All Women's Shoes
3           Shoes,Clothing,Women's Shoes,All Women's Shoes
4           Shoes,Women's Shoes,Clothing,All Women's Shoes
                               ...
19040    Watches,Clothing, Shoes & Jewelry,Women,Wrist ...
19041       Shoes,Clothing,Women's Shoes,All Women's Shoes
19042       Shoes,Clothing,Women's Shoes,All Women's Shoes
19043       Shoes,Clothing,Women's Shoes,All Women's Shoes
19044       Shoes,Clothing,Women's Shoes,All Women's Shoes
Name: categories, Length: 19045, dtype: object

In [75]:
women_shoe_df["category"] = "women"
women_shoe_df.head()

,id,asins,brand,categories,colors,count,dateadded,dateupdated,descriptions,dimension,...,prices_warranty,quantities,reviews,sizes,skus,sourceurls,upc,websiteids,weight,category
0,AVpfBXx21cnluZ0-cKxs,NaN,Zoot,Women,"Blue,Multicolor",NaN,2016-11-11T09:49:00Z,2016-11-11T09:49:00Z,"[{""dateSeen"":[""2016-11-11T09:49:00Z""],""sourceU...",NaN,...,NaN,NaN,NaN,"10,9",NaN,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN,women
1,AVpfBXx21cnluZ0-cKxs,NaN,Zoot,Women,"Blue,Multicolor",NaN,2016-11-11T09:49:00Z,2016-11-11T09:49:00Z,"[{""dateSeen"":[""2016-11-11T09:49:00Z""],""sourceU...",NaN,...,NaN,NaN,NaN,"10,9",NaN,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN,women
2,AVpfBXx21cnluZ0-cKxs,NaN,Zoot,Women,"Blue,Multicolor",NaN,2016-11-11T09:49:00Z,2016-11-11T09:49:00Z,"[{""dateSeen"":[""2016-11-11T09:49:00Z""],""sourceU...",NaN,...,NaN,NaN,NaN,"10,9",NaN,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN,women
3,AVpfBXx21cnluZ0-cKxs,NaN,Zoot,Women,"Blue,Multicolor",NaN,2016-11-11T09:49:00Z,2016-11-11T09:49:00Z,"[{""dateSeen"":[""2016-11-11T09:49:00Z""],""sourceU...",NaN,...,NaN,NaN,NaN,"10,9",NaN,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN,women
4,AVpfEqFRLJeJML431x7w,NaN,Wild Pair,"Shoes,Women's Shoes,Clothing,All Women's Shoes",Brown,NaN,2016-11-16T12:56:36Z,2016-11-16T12:56:36Z,"[{""dateSeen"":[""2016-11-16T12:56:36Z""],""sourceU...",NaN,...,NaN,NaN,NaN,"8.5,7,7.5,8",NaN,https://www.walmart.com/ip/Wild-Pair-Colfax-Wo...,7.63181E+11,NaN,NaN,women

In [76]:
#replace value in 'category' to 'women'

# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["#175 in,#4,521 in,#491 in,#11551 in,#1493 in,Shoes,#672 in,Clothing,Women's Shoes,All Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["#182 in,#2180 in,Shoes,#34 in,#2,180 in,Clothing,Women's Shoes,All Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["#244 in,#766 in,#6,326 in,#6326 in,Shoes,Women's Boots,Women's Shoes,Clothing,All Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["#5058 in,#29262 in,#2616 in,Shoes,Women's Boots,Women's Shoes,Clothing,All Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["#5111 in,#50297 in,Shoes,#10000 in,Women's Shoes,Clothing,All Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["#51626 in,#12257 in,#6796 in,Shoes,Women's Boots,Clothing,Women's Shoes,All Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["#5974 in,#5,974 in,#314 in,#701 in,Shoes,Clothing,Women's Shoes,All Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["#805 in,#312 in,Shoes,Clothing,Women's Shoes,#6,885 in,All Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Access.,Clothing,Shoes,Women's Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Accessories,Bags & Accessories,Gloves,Shoes,Women's Shoes,Clothing,All Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Accessories,Gloves,Bags & Accessories,Clothing, Shoes & Jewelry,Women's Accessories,Women's Gloves & Mittens,Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Accessories,Prescription Eyewear Frames,Women,Clothing, Shoes & Jewelry,Sunglasses & Eyewear Accessories,Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Accessories,Prescription Eyewear Frames,Women,Clothing, Shoes & Jewelry,Sunglasses & Eyewear Accessories,Sports"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Accessories,Prescription Eyewear Frames,Women,Contemporary & Designer,Clothing, Shoes & Jewelry,Sunglasses & Eyewear Accessories,Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Accessories,Prescription Eyewear Frames,Women,Shoes,Clothing, Shoes & Jewelry,Sunglasses & Eyewear Accessories"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Accessories,Sunglasses,Men,Women,Shoes,Clothing, Shoes & Jewelry,Sunglasses & Eyewear Accessories"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Accessories,Sunglasses,Women,Clothing, Shoes & Jewelry,Sports,Sunglasses & Eyewear Accessories"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Accessories,Sunglasses,Women,Clothing, Shoes & Jewelry,Sunglasses & Eyewear Accessories,Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Accessories,Sunglasses,Women,Safety Gear,Workwear, Safety Gear & Equipment,Clothing, Shoes & Jewelry,Sunglasses & Eyewear Accessories,Tools & Hardware,Clothing,Safety Glasses & Sunglasses,Health,Walmart Vision Centers"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Accessories,Women,Replacement Sunglass Lenses,Clothing, Shoes & Jewelry,Sunglasses & Eyewear Accessories"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Accessories,Women,Vision Care,Health & Personal Care,Clothing, Shoes & Jewelry,Sports,Sunglasses & Eyewear Accessories,Eyeglass Chains"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Active & Performance,Coats, Jackets & Vests,Women,Clothing, Shoes & Jewelry,Clothing,Fleece"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Active & Performance,Coats, Jackets & Vests,Women,Clothing, Shoes & Jewelry,Sports,Clothing,Fleece"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Active & Performance,Coats, Jackets & Vests,Women,Sweatshirts,Clothing, Shoes & Jewelry,Sports,Clothing,Fleece"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Active,Active Pants,Women,Clothing, Shoes & Jewelry,Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Active,Active Pants,Women,Clothing, Shoes & Jewelry,Sports,Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Active,Active Pants,Women's Activewear,Women,Clothing, Shoes & Jewelry,Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Active,Track & Active Jackets,Women,Clothing, Shoes & Jewelry,Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Active,Women,Active Base Layers,Clothing, Shoes & Jewelry,Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Active,Women,Active Leggings,Clothing, Shoes & Jewelry,Sports,Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Active,Women,Active Sweatshirts,Clothing, Shoes & Jewelry,Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Active,Women,Clothing, Shoes & Jewelry,Active Shorts,Sports,Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Active,Women,Clothing, Shoes & Jewelry,Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Adult Halloween Costumes,Clothing, Shoes & Accessories,Halloween,Costumes, Reenactment, Theater,Women,All Costumes,Costumes,Women's Halloween Costumes,Party & Occasions"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Adult Halloween Costumes,Clothing, Shoes & Accessories,Halloween,Men,Costumes, Reenactment, Theater,All Costumes,Costumes,Women's Halloween Costumes,Party & Occasions"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Adult Halloween Costumes,Halloween,All Costumes,Shoes,Women's Halloween Costumes,Clothing,Women's Shoes,Party & Occasions,All Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Adult Halloween Costumes,Halloween,All Costumes,Shoes,Women's Halloween Costumes,Party & Occasions,Women's Shoes,Clothing,All Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Adult Halloween Costumes,Halloween,All Costumes,Women's Halloween Costumes,Party & Occasions,Clothing, Shoes & Accessories"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["All Action Sports,Outlet,Shoes Outlet,All Shoes,Women's Shoes,Action Sports Outlet"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["All Juniors' Clothing,Women's Clothing,Juniors Skirts,Clothing, Shoes & Jewelry,Clothing,Women's Skirts,Juniors Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["All Juniors' Clothing,Women's Clothing,Juniors Skirts,Clothing, Shoes & Jewelry,Women's Skirts,Clothing,Juniors Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["All Juniors' Clothing,Women's Clothing,Plus Size Jeans,Juniors Plus Jeans,Juniors Jeans,Plus Size Clothing,Clothing, Shoes & Jewelry,Juniors Plus Clothing,Clothing,Juniors Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["All Juniors' Clothing,Women's Clothing,Women's Outerwear,Clothing, Shoes & Jewelry,Juniors Outerwear,Clothing,Juniors Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["All Juniors' Clothing,Women's Clothing,Women's Outerwear,Clothing, Shoes & Jewelry,Juniors Outerwear,Women's Coats & Jackets,Clothing,Juniors Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["All Juniors' Clothing,Women's Clothing,Women's Pants & Leggings,Juniors Jeans,All Women's Clothing,Clothing, Shoes & Jewelry,Clothing,Women's Jeans,Juniors Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["All Juniors' Clothing,Women's Clothing,Women's Pants & Leggings,Juniors Jeans,Clothing, Shoes & Jewelry,Clothing,Women's Jeans,Juniors Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["All Juniors' Clothing,Women's Clothing,Women's Pants & Leggings,Juniors Jeans,Clothing, Shoes & Jewelry,Women's Jeans,Clothing,Juniors Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["All Men's Clothing,Men's Clothing,Men's Outerwear,Bags & Accessories,Women's Scarves & Wraps,Clothing, Shoes & Jewelry,Women's Accessories,Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["All Men's Clothing,Men's Clothing,Women's Clothing,All Women's Clothing,Clothing, Shoes & Jewelry,Clothing,Women's Blazers, Jackets & Vests"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["All Men's Shoes,Shoes,Men's Shoes,Clothing,Women's Shoes,All Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["All Men's Shoes,Shoes,Men's Shoes,Women's Boots,Women's Shoes,Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["All Men's Shoes,Shoes,Men's Shoes,Women's Shoes,Clothing,All Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["All Men's Shoes,Shoes,Men's Shoes,Women's Shoes,Clothing,All Women's Shoes,Sneakers & Athletic Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["All Men's Shoes,Women's Slippers,Shoes,Men's Shoes,Women's Shoes,Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Ankle & Bootie,Women,Shoes,Clothing, Shoes & Jewelry,Boots"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Athletic & Outdoor Shoes,Trekking & Hiking Boots,Shoes,Trekking & Hiking Footwear,Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Athletic & Outdoor Shoes,Trekking & Hiking Footwear,Shoes,Women's Shoes,Trekking & Hiking Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Athletic & Running Shoes,Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Athletic & Running Shoes,Women's Shoes,Basketball Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Athletic & Running Shoes,Women's Shoes,Cross-Training Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Athletic & Running Shoes,Women's Shoes,Running Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Athletic & Running Shoes,Women's Shoes,Slides & Sandals"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Athletic & Running Shoes,Women's Shoes,Slippers"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Athletic Shoes,Women,Workout, Yoga & Outdoor"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Athletic,Clothing, Shoes & Accessories,Team Sports,Women,Soccer,Shoes & Cleats,Sporting Goods,Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Athletic,Clothing, Shoes & Accessories,Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Athletic,Fitness & Cross-Training,Women,Shoes,Clothing, Shoes & Jewelry"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Athletic,Running,Women,Shoes,Clothing, Shoes & Jewelry"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Athletic,Running,Women,Shoes,Clothing, Shoes & Jewelry,Sports"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Athletic,Skateboarding,Women,Shoes,Clothing, Shoes & Jewelry"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Athletic,Skateboarding,Women,Shoes,Clothing, Shoes & Jewelry,Clothing,Women's Shoes,All Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Athletic,Water Shoes,Women,Shoes,Clothing, Shoes & Jewelry"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Athletic,Women,Shoes,Clothing, Shoes & Jewelry"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Athletic,Women,Shoes,Clothing, Shoes & Jewelry,Racquet Sports"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Athletic,Women,Shoes,Racquet Sports,Clothing, Shoes & Jewelry"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Athletic,Women,Shoes,Shoes & Handbags"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Athletic,Women,Walking,Shoes,Clothing, Shoes & Jewelry"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Baby,Feeding,Breastfeeding,Clothing, Shoes & Jewelry,Clothing,Women's Clothing,Maternity & Nursing Clothing,Nursing Clothing & Supplies,Nursing Supplies"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Baby,Feeding,Nursing Pillows & Covers,Bedding,Pillows,Clothing, Shoes & Jewelry,Clothing,Women's Clothing,Maternity & Nursing Clothing,Nursing Clothing & Supplies,Nursing Supplies"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Bags  Shoes,Women's Bags  Shoes,Handbags"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Bags & Accessories,Clothing, Shoes & Jewelry,Women's Accessories,Women's Messenger Bags & Backpacks"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Bags & Accessories,Clothing, Shoes & Jewelry,Women's Gloves & Mittens,Women's Accessories"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Bags & Accessories,Shoes,Handbags,Clothing,Women's Shoes,All Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Bags & Accessories,Shoes,Handbags,Women's Boots,Women's Shoes,Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Bags & Accessories,Women's Scarves & Wraps,Clothing, Shoes & Jewelry,Women's Accessories"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Ballet & Dance,Athletic,Women,Shoes,Clothing, Shoes & Jewelry"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Ballets, Flats & Sneakers,Women,Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Bands,Fine,Women,Rings,Clothing, Shoes & Jewelry,Jewelry"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Bands,Women,Fashion,Rings,Clothing, Shoes & Jewelry,Jewelry"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Baseball Caps,Cycling,Accessories,Men,Women,Clothing, Shoes & Jewelry,Caps,Sports & Outdoors,Hats & Caps,Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Beauty,Hair Care,Hair Accessories,Clothing, Shoes & Jewelry,Bags & Accessories,Women's Accessories,Women's Hair Accessories"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Blazers,Suiting & Blazers,Women,Clothing, Shoes & Jewelry,Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Boat Shoes,Women's Athletic Shoes,Shoes,Women's Shoes,Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Bodysuits,Lingerie, Sleep & Lounge,Women,Clothing, Shoes & Jewelry,Clothing,Lingerie,Shapewear"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Booties,Shoes,Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Boots,Athletic & Running Shoes,Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Boots,Clothing,Shoes,Women's Shoes,All Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Boots,Clothing,Shoes,Women's Shoes,Women's Boots"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Boots,Shoes,Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Boots,Women's Shoes,Athletic & Running Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Bra Extenders,Accessories,Lingerie, Sleep & Lounge,Women,Clothing, Shoes & Jewelry,Lingerie,Clothing,Craft Supplies,Arts,,Arts, Crafts & Sewing,Home & Kitchen"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Braces & Supports,Clothing, Shoes & Accessories,Women's Clothing,Intimates & Sleep,Medical, Mobility & Disability,Health & Beauty,Shapewear"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Braces & Supports,Orthopedics & Supports,Clothing, Shoes & Accessories,Orthotics, Braces & Sleeves,Women's Clothing,Intimates & Sleep,Medical, Mobility & Disability,Health & Beauty,Shapewear"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Braces & Supports,Women's Casual Shoes,Medical, Mobility & Disability,Shoes,Health & Beauty,Clothing,Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Breastfeeding,Nursing Supplies,Feeding,Baby,Women's Clothing,Maternity & Nursing Clothing,Clothing, Shoes & Jewelry,Clothing,Nursing Clothing & Supplies"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Briefs & Undergarments,Women's Pants,Incontinence,All Juniors' Clothing,Women's Clothing,Women's Pants & Leggings,Health & Wellness,Juniors Pants & Leggings,Clothing, Shoes & Jewelry,Clothing,Juniors Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["By Personality,Women's Casual Shoes,Gifts,Women's,Shoes,For Her,Clothing, Shoes & Jewelry,Women's Boots,Women's Shoes,Trendsetter,By Recipient"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["By Personality,Women's Casual Shoes,Gifts,Women's,Shoes,For Her,Clothing, Shoes & Jewelry,Women's Flats,Women's Shoes,Trendsetter,By Recipient"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Casual,Women,Contemporary & Designer,Pants,Clothing, Shoes & Jewelry,Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Casual,Women,Pants,Clothing, Shoes & Jewelry,Sports,Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Cell,Clothing, Shoes & Jewelry,Women,Watches,Wrist Watches"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Chains,Novelty & More,Necklaces & Pendants,Women,Fashion,Clothing, Shoes & Jewelry,Jewelry,Necklaces"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Chains,Novelty & More,Women,Necklaces & Pendants,Fashion,Clothing, Shoes & Jewelry,Necklaces,Jewelry"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Chains,Women,Fashion,Clothing, Shoes & Jewelry,Jewelry,Necklaces"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Chains,Women,Fashion,Clothing, Shoes & Jewelry,Necklaces,Jewelry"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Charms & Charm Bracelets,Charm Bracelets,Women,Fashion,Clothing, Shoes & Jewelry,Jewelry"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Charms & Charm Bracelets,Snake,Charm Bracelets,Women,Fashion,Clothing, Shoes & Jewelry,Jewelry"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Chokers,Women,Fashion,Clothing, Shoes & Jewelry,Jewelry,Necklaces"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Climbing,Women,Shoes,Outdoor,Clothing, Shoes & Jewelry"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clogs,Shoes,Clothing,Women's Shoes,All Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing & Accessories,Novelty, Costumes & More,Adult Halloween Costumes,Clothing, Shoes & Accessories,Halloween,Costumes, Reenactment, Theater,Women,All Costumes,Costumes,Women's Halloween Costumes,Party & Occasions"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Adult Halloween Costumes,Halloween,Costumes, Reenactment, Theater,Girls,All Costumes,Costumes,Women's Halloween Costumes,Party & Occasions"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Adult Halloween Costumes,Halloween,Costumes, Reenactment, Theater,See more Deluxe Arwen Gown Lord of the Rings Adult Wome...,Women,All Costumes,Costumes,Women's Halloween Costumes,Party & Occasions"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Adult Halloween Costumes,Halloween,Costumes, Reenactment, Theater,Women,All Costumes,Costumes,Women's Halloween Costumes,Party & Occasions"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Adult Halloween Costumes,Halloween,See more SPOILED FAIRY ADULT WOMENS COSTUME Magical Fai...,Costumes, Reenactment, Theater,Women,All Costumes,Costumes,Women's Halloween Costumes,Party & Occasions"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Athletic Apparel,Team Sports,Women's Clothing,Women,Soccer,Sporting Goods,Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Athletic Apparel,Women's Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Athletic Apparel,Women's Clothing,Clothing & Accessories,Fitness, Running & Yoga,Compression & Base Layers,Sporting Goods"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Athletic,Shoes,Women's Shoes,Clothing,All Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Athletic,Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Bags Fan Shop,Sports Fan Shop,Travel & Shopping Bags,Women's Handbags & Bags,Clothing Fan Shop,Sports & Outdoors,Reusable Eco Bags"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Boots,Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Bras & Bra Sets,All Bras,Women's Clothing,Intimates & Sleep,Clothing,Intimates & Sleepwear,Bras"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Bras & Bra Sets,Women's Clothing,Intimates & Sleep"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Bras & Bra Sets,Women's Clothing,Intimates & Sleep,Women"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Briefcases & Laptop Bags,Women's Handbags & Bags,Men's Accessories,Backpacks, Bags & Briefcases"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Classics,Holiday Shops,Costumes, Reenactment, Theater,Women,Halloween Store,Costumes,Womens Costumes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Classics,Holiday Shops,Costumes, Reenactment, Theater,Women,Halloween Store,See more Rasta Imposta Flag USA Dress Red White Blue Wo...,Costumes,Womens Costumes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Costumes, Reenactment, Theater,Accessories,Masks & Eye Masks,See more Rbenxia Women Girl Lace Eyemask Eye Mask for H..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Costumes, Reenactment, Theater,Costumes,Women"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Costumes, Reenactment, Theater,Costumes,Women,Adult Halloween Costumes,Halloween,#4260 in,All Costumes,#3478 in,Women's Halloween Costumes,#12050 in,Party & Occasions"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Costumes, Reenactment, Theater,Costumes,Women,See more RG Costumes 78138-p 50s Pink Poodle Skirt - Si..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Costumes, Reenactment, Theater,Pretend Play & Dress Up,Women,Costumes,Toys"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Costumes, Reenactment, Theater,Women,Costumes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Flats & Oxfords,Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Hair Accessories,Hair Care,Hair Brushes & Styling Accessories,Beauty,Women's Accessories"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Hair Accessories,Hair Care,Hair Brushes & Styling Accessories,Beauty,Women's Accessories,Health & Beauty"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Hair Accessories,Kids' Clothing, Shoes & Accs,Women's Accessories,Girls' Accessories"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Hair Accessories,Women's Accessories"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Halloween,All Halloween Costumes,Costumes, Reenactment, Theater,Women,All Costumes,Costumes,Party & Occasions"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Heels,Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Intimates,Women's Clothing,Costumes, Reenactment, Theater,Wholesale, Large & Small Lots,Women,Costumes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Intimates,Women's Clothing,Wholesale, Large & Small Lots"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Jeans,Women's Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Men's Accessories,Backpacks, Bags & Briefcases,Women's Handbags & Bags"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Men's Accessories,Backpacks, Bags & Briefcases,Women's Handbags & Bags,Briefcases & Laptop Bags"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Men's Accessories,Sunglasses & Fashion Eyewear,Sunglasses,Women's Accessories"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Occupational,Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Other Whlsl Women's Clothing,Women's Clothing,Wholesale, Large & Small Lots"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Sandals & Flip Flops,See more Baretraps Sinclair Womens Size 8 Black Leather...,Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Sandals & Flip Flops,Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Sandals & Flip Flops,Women's Shoes,See more Aerosoles On Stage Women US 10 White Slides Sa..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Scarves & Wraps,Women's Accessories"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Scarves, Wraps,Accessories,Women's Accessories, Handbags,Wholesale, Large & Small Lots,Bags & Accessories,Cold Weather Accessories,Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Scarves, Wraps,Women's Accessories, Handbags,Wholesale, Large & Small Lots"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,See more Assets 8129 Womens Black Luxe & Lean Super Sli...,Women's Clothing,Intimates & Sleep,Slips"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,See more Gucci Women's Aviator Sunglasses,Sunglasses,Walmart Vision Centers,Sunglasses & Fashion Eyewear,Unisex Accessories,Unisex Clothing, Shoes & Accs,Health"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,See more Karen Scott 2843 Womens Blue Cargo Drawstring ...,Women's Clothing,Shorts"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Shoes,Boots,Clothing,Women's Shoes,All Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Shoes,Boots,Women's Shoes,Clothing,All Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Stockings,1977-89 (Punk, New Wave, 80s),Women's Clothing,Hosiery & Socks,Women's Vintage Clothing,Pantyhose & Tights,Lingerie,Vintage"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Sunglasses & Fashion Eyewear,Eyewear Accessories,Women's Accessories"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Sunglasses,See more BWT Michael Kors Mk5005 Sunglasses Gold Brown ...,Sunglasses & Fashion Eyewear,Women's Accessories"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Sunglasses,Sunglasses & Fashion Eyewear,Men's Accessories,Women's Accessories"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Sunglasses,Sunglasses & Fashion Eyewear,Walmart Vision Centers,Health,Women's Accessories"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Sunglasses,Sunglasses & Fashion Eyewear,Walmart Vision Centers,Men's Accessories,Health,Women's Accessories"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Sunglasses,Sunglasses & Fashion Eyewear,Women's Accessories"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Sunglasses,Walmart Vision Centers,Sunglasses & Fashion Eyewear,Health,Men's Accessories,Women's Accessories"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Sunglasses,Walmart Vision Centers,Sunglasses & Fashion Eyewear,Health,Women's Accessories"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Sunglasses,Walmart Vision Centers,Sunglasses & Fashion Eyewear,Ralph,Health,4004,Women's Accessories"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Team Sports,Women,Soccer,Shoes & Cleats,Sporting Goods"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Travel & Shopping Bags,Women's Handbags & Bags,Reusable Eco Bags"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Unisex Clothing, Shoes & Accs,Unisex Accessories,Sunglasses & Fashion Eyewear,Sunglasses,shop hers, all women's"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Vintage,Women's Vintage Clothing,Lingerie,Pantyhose & Stockings"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Wholesale, Large & Small Lots,Women's Accessories, Handbags,Handbags, Bags"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Wholesale, Large & Small Lots,Women's Accessories, Handbags,Other Wholesale Women's Accs"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Wholesale, Large & Small Lots,Women's Accessories, Handbags,Scarves, Wraps"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Wholesale, Large & Small Lots,Women's Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Accessories, Handbags,Wholesale, Large & Small Lots,Handbags, Bags"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Accessories, Handbags,Wholesale, Large & Small Lots,Other Wholesale Women's Accs"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Accessories,Gloves & Mittens"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Accessories,Hair Accessories"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Accessories,Hats"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Accessories,Key Chains, Rings & Finders"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Accessories,Scarves & Wraps"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Accessories,Scarves & Wraps,Men's Accessories,Scarves"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Accessories,Sunglasses & Fashion Eyewear,Fashion Eyewear/Clear Glasses,Unisex Clothing, Shoes & Accs,Unisex Accessories,Sunglasses"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Accessories,Sunglasses & Fashion Eyewear,Sunglasses"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Accessories,Sunglasses & Fashion Eyewear,Sunglasses,See more GUESS Women's Brncy Oval Sunglasses GU 7250 62..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Accessories,Sunglasses & Fashion Eyewear,Sunglasses,See more PRADA PR 12qs Cinema Tkp4k0 Opal Pink and Matt..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Accessories,Sunglasses & Fashion Eyewear,Sunglasses,See more PRADA Sunglasses Spr 01q Cast Gray Dg70a7 Auth..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Accessories,Sunglasses & Fashion Eyewear,Sunglasses,shop hers, all women's"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Accessories,Sunglasses & Fashion Eyewear,Sunglasses,Wholesale, Large & Small Lots,Mixed Lots"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Accessories,Wigs, Extensions & Supplies,Women's Hair Extensions"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Accessories,Wigs, Extensions & Supplies,Women's Wigs"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Athletic Apparel"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Athletic Apparel,See more Ideology Womens Pink Space Dye 6521 Performanc..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Athletic Apparel,See more U.s. Polo Assn. 6450 Womens Gray Heathered Ruc..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Athletic Apparel,Sporting Goods,Fitness, Running & Yoga,Clothing & Accessories,Pants"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Coats & Jackets"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Coats & Jackets,See more Bar III Womens Black Solid 6422 Notched Lapel ..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Coats & Jackets,See more Calvin Klein Blue Lagoon Women's Size 2x Plus ..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Coats & Jackets,Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Coats & Jackets,Sporting Goods,Outdoor Sports,Camping & Hiking,Clothing,Women's"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Coats & Jackets,Suits & Blazers"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Hosiery & Socks,Pantyhose & Tights"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Hosiery & Socks,Pantyhose & Tights,See more SPANX Size E Black In-power Super High Shaping..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Hosiery & Socks,Socks"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Hosiery & Socks,Socks,See more 3 Pair Nike White Soft Dry Socks Crew Sx4700-1..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Hosiery & Socks,Socks,See more Anne Klein 3000 Womens Gray Heathered Striped ..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Intimates & Sleep,Bras & Bra Sets"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Intimates & Sleep,Bras & Bra Sets,See more 2 Bali Comfort Revolution Convertible Wirefree..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Intimates & Sleep,Bras & Bra Sets,See more Bali Bra 38c Comfort Revolution 3550 Stretch F..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Intimates & Sleep,Bras & Bra Sets,See more Fantasie 9002 Eclipse Underwired Spacer MOULDE..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Intimates & Sleep,Bras & Bra Sets,See more Glamorise Bra 52b 52c 52 B-c Stretch Lace Supp..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Intimates & Sleep,Bras & Bra Sets,See more Lilyette 38ddd White Comfort Lace Minimizer Br...,Women"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Intimates & Sleep,Bras & Bra Sets,See more VS Victoria's Secret Body by Victoria Unlined ..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Intimates & Sleep,Bras & Bra Sets,See more Wonderbra Plus 1983 Full Figured No Poke Under..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Intimates & Sleep,Breast Forms, Enhancers"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Intimates & Sleep,Panties"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Intimates & Sleep,Panties,See more Briefly Stated Peanuts Women's Snoopy Hipster ..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Intimates & Sleep,Panties,See more Olga 873 Secret Hug Nylon Scoop Full Brief Pan..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Intimates & Sleep,Shapewear"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Intimates & Sleep,Sleepwear & Robes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Intimates & Sleep,Teddies"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Intimates & Sleep,Teddies,See more Mesh Halter Neck Teddy Hearts Print Cutout Ruf..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Jeans"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Jeans,Juniors"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Jeans,See more Lucky BRAND 7wc1012 Sofia Boot Dark Wash Denim..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Jeans,See more NWD Womens Chaps Denim BOYFRIEND Fit Jeans 210..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Jeans,See more Tommy Hilfiger 6088 Womens White Denim Low-ris..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Jumpsuits & Rompers"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Leggings"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Pants"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Pants,See more ALFRED DUNNER 8927 Womens Yellow Solid Flat Fr..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Pants,See more Elizabeth and James 9770 Womens Johnny Blue Wo..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Pants,See more Jolt Beige Size 1 Junior Flat-front Seamed Cro..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Pants,See more People Ob397356 Printed Asymmetrical Culottes ..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Pants,See more Ralph Lauren Jacie Dress Pants Trousers Gray G..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Pants,See more Tahari ASL 4300 Womens Trey Black Ponte Wide L...,Women"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Pants,See more Women Plus Size Alfani Tummy Control Capri Pan..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,See more Leg Avenue 1905q Plus Size Sheer Nylon Crotchl...,Hosiery & Socks,Pantyhose & Tights"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Shorts"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Shorts,See more Jolt Black Ivory Girls Junior Zips in The Back..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Shorts,See more Tommy Hilfiger Size 10 Fuchsia Solid Bermuda S..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Skirts"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Skirts,See more Elie Tahari 7104 Womens Kim B W Scuba Reversib..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Sleepwear & Robes,Intimates & Sleep"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Stockings & Thigh-Highs,Hosiery & Socks,Socks & Hosiery,See more Leg Avenue 6600 Acrylic Neon Rainbow Thigh Hig...,Clothing,Intimates & Sleepwear"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Suits & Blazers"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Suits & Blazers,See more Laundry by Shelli Segal 6999 Womens White Crep..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Suits & Blazers,See more Le Suit 2452 Womens Red Woven Checkered Mid Ca..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Suits & Blazers,See more Le Suit 4003 Womens Taupe Herringbone Three-bu..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Suits & Blazers,See more Le Suit 6422 Womens Yatch Club Green Three-but..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Suits & Blazers,See more Le Suit 8811 Womens City Blooms Yellow Scallop..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Suits & Blazers,See more Marina 1690 Womens Black Mesh Sequined Open Fr..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Suits & Blazers,See more Tahari ASL Asymmetrical Buttons Pant Suit Set ..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Suits & Blazers,See more Tahari Women's Skirt Suit Sz 12"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Sweats & Hoodies"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Sweats & Hoodies,See more Juicy Couture Black Label 4730 Womens Couture ..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Swimwear"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Swimwear,See more La Blanca Women Black 1 PC Halter Top Straples..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Swimwear,See more Women's TYR Durafast Diamondfit Workout Compet..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Clothing,Wholesale, Large & Small Lots,Swimwear"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Hair Extensions,Women's Accessories,Wigs, Extensions & Supplies"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Handbags & Bags"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Handbags & Bags,Backpacks & Bookbags"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Handbags & Bags,Backpacks & Bookbags,Men's Accessories,Backpacks, Bags & Briefcases"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Handbags & Bags,Backpacks & Bookbags,See more KAVU Rope Bag - Hodgepodge"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Handbags & Bags,Backpacks & Bookbags,See more KAVU Rope Bag - Razzmatazz"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Handbags & Bags,Backpacks & Bookbags,Unisex Clothing, Shoes & Accs,Unisex Accessories,Bags & Backpacks"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Handbags & Bags,Diaper Bags"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Handbags & Bags,Handbag Accessories"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Handbags & Bags,Handbag Accessories,Jewelry & Watches,Jewelry Boxes & Organizers,Jewelry Holders & Organizers,Multi-Purpose"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Handbags & Bags,Travel & Shopping Bags,Duffel & Gym Bags"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Handbags & Bags,Travel & Shopping Bags,Duffel & Gym Bags,See more Vera Bradley Tech Organizer Blue Lagoon Access..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Handbags & Bags,Travel & Shopping Bags,Fanny, Waist Packs"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Athletic"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Athletic,See more Easy Street Kacey Women's Size 11w Wide"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Athletic,See more Merrell Womens All out Blaze Mid Waterproof Br..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Athletic,See more Ryka Hydro Sport Blue Silver Womens Training S..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Athletic,See more VANS Authentic Lo Pro Cosmic Galaxy Black Blue..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Athletic,Unisex Clothing, Shoes & Accs,Unisex Adult Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Boots"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Boots,See more Bogs 1654 Womens Gray Plaid Waterproof Rubber ..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Boots,See more Easy Spirit 6010 Womens Elk Black Suede Winter..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Boots,See more Frye Jenna Cut Stud Short Distressed Stonewash..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Boots,See more LifeStride 9770 Womens Sasha Black Riding BOOT..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Boots,See more Marc Fisher Frenchie Women US 7.5 Black Ankle ..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Boots,See more Marc Fisher Kessler Womens Size 10 Brown Leath..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Boots,See more Michael Kors Fulton Harness Rainbootie Black W..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Boots,See more Pajar 1695 Womens Iceberg Brown Suede Winter B..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Boots,See more Penny Loves Kenny 3560 Womens Dallas Black Qui..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Boots,See more Sam Edelman 8902 Womens Petty Black Suede BOOT..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Boots,See more Tecnica Moon Boot Nylon White Womens Winter BO..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Boots,See more Timberland Glancy 6 Inch BOOTS Black Women's L..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Flats & Oxfords"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Flats & Oxfords,Sandals & Flip Flops"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Flats & Oxfords,See more Michael Kors Fulton MOC Washed Denim Shoes Fla..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Flats & Oxfords,See more SeaVees 6086 Womens Villager Brown Canvas Leat..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Flats & Oxfords,See more Steve Madden Evrlast Women US 6 Gold Flats Ble..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Flats & Oxfords,See more Via Spiga Lilac Womens Size 7 Silver Leather B..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Flats & Oxfords,Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Heels"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Heels,See more Auth Gucci Women Patent Leather High Heel Shoe..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Heels,See more Jessica Simpson Sabella Women US 7.5 Nude Pre ..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Heels,See more Louise Et Cie Esperance Women US 10.5 Black Sl..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Heels,Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Occupational"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Sandals & Flip Flops"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Sandals & Flip Flops,See more Clarks Brinkley Jazz Women US 8 White Flip Flo..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Sandals & Flip Flops,See more Kenneth Cole Reactio Slim Shake Women US 7 Bla..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Sandals & Flip Flops,See more Michael Kors 4550 Womens Charlene Ivory Caged ..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Sandals & Flip Flops,See more Rebels 1906 Womens Paityn Orange Leather Dress..."],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Sandals & Flip Flops,Shoes"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Shoes,Slippers"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Accessories,Women's Wigs,Women's Accessories,Wigs, Extensions & Supplies"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Jewelry,Bags & Accessories,Women's Accessories,Women's Hair Accessories"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Jewelry,Bags & Accessories,Women's Accessories,Women's Hats"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Jewelry,Bags & Accessories,Women's Accessories,Women's Scarves & Wraps"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Jewelry,Bags & Accessories,Women's Accessories,Women's Sunglasses,Sunglasses"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Jewelry,Clothing,Juniors Clothing,Juniors Pants & Leggings,Women's Clothing,Women's Pants & Leggings,Women's Leggings,Women's Pants,All Juniors' Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Jewelry,Clothing,Women's Clothing,All Women's Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Jewelry,Clothing,Women's Clothing,Intimates & Sleepwear,Bras,All Women's Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Jewelry,Clothing,Women's Clothing,Intimates & Sleepwear,Intimates Accessories,All Women's Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Jewelry,Clothing,Women's Clothing,Intimates & Sleepwear,Lingerie,All Women's Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Jewelry,Clothing,Women's Clothing,Intimates & Sleepwear,Panties"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Jewelry,Clothing,Women's Clothing,Intimates & Sleepwear,Panties,All Women's Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Jewelry,Clothing,Women's Clothing,Intimates & Sleepwear,Slips"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Jewelry,Clothing,Women's Clothing,Intimates & Sleepwear,Women's Sleepwear & Robes,Women's Sleepwear,All Women's Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Jewelry,Clothing,Women's Clothing,Plus Size Clothing,Plus Size Activewear"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Jewelry,Clothing,Women's Clothing,Plus Size Clothing,Plus Size Blazers, Jackets & Vests,Women's Blazers, Jackets & Vests,All Women's Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Jewelry,Clothing,Women's Clothing,Plus Size Clothing,Plus Size Pants & Leggings"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Jewelry,Clothing,Women's Clothing,Plus Size Clothing,Plus Size Pants & Leggings,Women's Pants & Leggings,Women's Pants,All Women's Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Jewelry,Clothing,Women's Clothing,Plus Size Clothing,Plus Size Shorts & Capris,Women's Shorts & Capris,Women's Shorts & Skorts,All Women's Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Jewelry,Clothing,Women's Clothing,Women's Activewear,All Women's Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Jewelry,Clothing,Women's Clothing,Women's Blazers, Jackets & Vests,All Women's Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Jewelry,Clothing,Women's Clothing,Women's Blazers, Jackets & Vests,Juniors Clothing,Juniors Blazers, Jackets & Vests,All Juniors' Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Jewelry,Clothing,Women's Clothing,Women's Blazers, Jackets & Vests,Petite Clothing,Petite Blazers, Jackets & Vests,All Women's Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Jewelry,Clothing,Women's Clothing,Women's Coats & Jackets,All Women's Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Jewelry,Clothing,Women's Clothing,Women's Jeans,Women's Pants & Leggings,All Women's Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Jewelry,Clothing,Women's Clothing,Women's Jeans,Women's Pants & Leggings,Juniors Clothing,Juniors Jeans,All Juniors' Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Jewelry,Clothing,Women's Clothing,Women's Jeans,Women's Pants & Leggings,Plus Size Clothing,Plus Size Jeans,All Women's Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Jewelry,Clothing,Women's Clothing,Women's Pants & Leggings,Women's Pants,All Women's Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Jewelry,Clothing,Women's Clothing,Women's Rompers & Jumpsuits,All Women's Clothing"],"Women")
# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Clothing, Shoes & Jewelry,Clothing,Women's Clothing,Women's Skirts,All Women's Clothing"],"Women")

# women_shoe_df['categories'] = women_shoe_df['categories'].replace(["Shoes,Clothing,Women's Shoes,All Women's Shoes"],"Women")

# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")
# # women_shoe_df['categories'] = women_shoe_df['categories'].replace([""],"Women")

In [77]:
# women_shoe_df

In [62]:
men_shoe_df["categories"]

0               Clothing,Shoes,Men's Shoes,All Men's Shoes
1               Clothing,Shoes,Men's Shoes,All Men's Shoes
2               All Men's Shoes,Shoes,Men's Shoes,Clothing
3               All Men's Shoes,Shoes,Men's Shoes,Clothing
4               All Men's Shoes,Shoes,Men's Shoes,Clothing
                               ...
19382      Clothing, Shoes & Accessories,Men's Shoes,Boots
19383           Clothing,Shoes,Men's Shoes,All Men's Shoes
19384    Women's Sunglasses,Sunglasses,Bags & Accessori...
19385    Women's Sunglasses,Sunglasses,Bags & Accessori...
19386    Women's Sunglasses,Sunglasses,Bags & Accessori...
Name: categories, Length: 19387, dtype: object

In [81]:
men_shoe_df["category"] = "men"
men_shoe_df.head()

,id,asins,brand,categories,colors,count,dateadded,dateupdated,descriptions,dimension,...,quantities,reviews,sizes,skus,sourceurls,upc,vin,websiteids,weight,category
0,AVpfHrJ6ilAPnD_xVXOI,NaN,Josmo,"Clothing,Shoes,Men's Shoes,All Men's Shoes",NaN,NaN,2016-11-07T00:45:12Z,2016-11-07T00:45:12Z,"[{""dateSeen"":[""2016-11-07T00:45:12Z""],""sourceU...",NaN,...,NaN,NaN,NaN,NaN,https://www.walmart.com/ip/Josmo-8190-Plain-In...,699302044036,NaN,NaN,NaN,men
1,AVpfHrJ6ilAPnD_xVXOI,NaN,Josmo,"Clothing,Shoes,Men's Shoes,All Men's Shoes",NaN,NaN,2016-11-07T00:45:12Z,2016-11-07T00:45:12Z,"[{""dateSeen"":[""2016-11-07T00:45:12Z""],""sourceU...",NaN,...,NaN,NaN,NaN,NaN,https://www.walmart.com/ip/Josmo-8190-Plain-In...,699302044036,NaN,NaN,NaN,men
2,AVpfHsWP1cnluZ0-eVZ7,NaN,SERVUS BY HONEYWELL,"All Men's Shoes,Shoes,Men's Shoes,Clothing",NaN,NaN,2016-06-14T04:29:57Z,2016-07-09T20:26:48Z,"[{""dateSeen"":[""2016-07-09T20:26:48Z""],""sourceU...",NaN,...,NaN,NaN,NaN,NaN,http://www.walmart.com/ip/Studs-Shoe-Large-Pr-...,NaN,NaN,NaN,NaN,men
3,AVpfHsWP1cnluZ0-eVZ7,NaN,SERVUS BY HONEYWELL,"All Men's Shoes,Shoes,Men's Shoes,Clothing",NaN,NaN,2016-06-14T04:29:57Z,2016-07-09T20:26:48Z,"[{""dateSeen"":[""2016-07-09T20:26:48Z""],""sourceU...",NaN,...,NaN,NaN,NaN,NaN,http://www.walmart.com/ip/Studs-Shoe-Large-Pr-...,NaN,NaN,NaN,NaN,men
4,AVpfHsWP1cnluZ0-eVZ7,NaN,SERVUS BY HONEYWELL,"All Men's Shoes,Shoes,Men's Shoes,Clothing",NaN,NaN,2016-06-14T04:29:57Z,2016-07-09T20:26:48Z,"[{""dateSeen"":[""2016-07-09T20:26:48Z""],""sourceU...",NaN,...,NaN,NaN,NaN,NaN,http://www.walmart.com/ip/Studs-Shoe-Large-Pr-...,NaN,NaN,NaN,NaN,men

### Transform women's shoes DataFrame

In [86]:
# Create a filtered dataframe from specific columns
women_shoe_cols = ["id", "brand", "category", "prices_amountmin", "prices_amountmax"]
women_shoe_transformed = women_shoe_df[women_shoe_cols].copy()

# Rename the column headers
women_shoe_transformed = women_shoe_transformed.rename(columns={"prices_amountmin": "($)prices_min",
                                                          "prices_amountmax": "($)prices_max"})

# Clean the data by dropping duplicates and setting the index
women_shoe_transformed.drop_duplicates("id", inplace=True)
women_shoe_transformed.set_index("id", inplace=True)

women_shoe_transformed.head()

                              brand category ($)prices_min ($)prices_max
id
AVpfBXx21cnluZ0-cKxs           Zoot    women         71.99         71.99
AVpfEqFRLJeJML431x7w      Wild Pair    women         26.98         26.98
AVpfFCfi1cnluZ0-dcCZ  Sutton Studio    women           318           318
AVpfBZCAilAPnD_xTN_K    LaLeela.com    women         27.98         27.98
AVpfHscY1cnluZ0-eVb6         Reebok    women         22.99         22.99

# Transform men's shoes DataFrame

In [84]:
# Create a filtered dataframe from specific columns
men_shoe_cols = ["id", "brand", "category", "prices_amountmin", "prices_amountmax"]
men_shoe_transformed = men_shoe_df[men_shoe_cols].copy()

# Rename the column headers
men_shoe_transformed = men_shoe_transformed.rename(columns={"prices_amountmin": "($)prices_min",
                                                          "prices_amountmax": "($)prices_max"})

# Clean the data by dropping duplicates and setting the index
men_shoe_transformed.drop_duplicates("id", inplace=True)
men_shoe_transformed.set_index("id", inplace=True)

men_shoe_transformed.head()

                                    brand category ($)prices_min ($)prices_max
id
AVpfHrJ6ilAPnD_xVXOI                Josmo      men         39.89         39.89
AVpfHsWP1cnluZ0-eVZ7  SERVUS BY HONEYWELL      men         40.02         40.02
AVpfAwehilAPnD_xS_eB               NATIVE      men         45.00         45.00
AVpfFCHeilAPnD_xUeS0        MAUI AND SONS      men          9.99          9.99
AVpfHssKilAPnD_xVXu5               Hao-bo      men         37.99         37.99

### changing value of categories from  women's shoes DataFrame

### Create database connection

In [87]:
protocol = 'postgresql'
username = 'postgres'
password = 'password'
host = 'localhost'
port = 5432
database_name = 'women_shoe_transformed'
rds_connection_string = f'{protocol}://{username}:{password}@{host}:{port}/{database_name}'
engine = create_engine(rds_connection_string)

In [88]:
# Confirm tables
inspector = inspect(engine)
inspector.get_table_names()

OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

(Background on this error at: https://sqlalche.me/e/14/e3q8)

### Load DataFrames into database

In [68]:
women_shoe_transformed.to_sql(name='women_shoe_transformed', con=engine, if_exists='append', index=True)

OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  database "                              brand  \
id                      " does not exist

(Background on this error at: https://sqlalche.me/e/14/e3q8)

In [69]:
men_shoe_transformed.to_sql(name='men_shoe_transformed', con=engine, if_exists='append', index=True)

OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  database "                              brand  \
id                      " does not exist

(Background on this error at: https://sqlalche.me/e/14/e3q8)