In [7]:
import pandas as pd
from sqlalchemy import create_engine, inspect

### Extract CSVs into DataFrames

In [8]:
man_shoe_file = "../Resources/7003_1.csv"
man_shoe_df = pd.read_csv(man_shoe_file)
man_shoe_df.head()

/var/folders/_3/fpx1kffx6n90zjt7rjys0h6r0000gn/T/ipykernel_16119/3663407765.py:2: DtypeWarning: Columns (25,36,39,44) have mixed types. Specify dtype option on import or set low_memory=False.
  man_shoe_df = pd.read_csv(man_shoe_file)

,id,asins,brand,categories,colors,count,dateadded,dateupdated,descriptions,dimension,...,prices_sourceurls,prices_warranty,quantities,reviews,sizes,skus,sourceurls,upc,websiteids,weight
0,AVpfBXx21cnluZ0-cKxs,NaN,Zoot,"Shoes,Clothing,Women's Shoes,All Women's Shoes","Blue,Multicolor",NaN,2016-11-11T09:49:00Z,2016-11-11T09:49:00Z,"[{""dateSeen"":[""2016-11-11T09:49:00Z""],""sourceU...",NaN,...,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN,"10,9",NaN,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN
1,AVpfBXx21cnluZ0-cKxs,NaN,Zoot,"Shoes,Clothing,Women's Shoes,All Women's Shoes","Blue,Multicolor",NaN,2016-11-11T09:49:00Z,2016-11-11T09:49:00Z,"[{""dateSeen"":[""2016-11-11T09:49:00Z""],""sourceU...",NaN,...,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN,"10,9",NaN,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN
2,AVpfBXx21cnluZ0-cKxs,NaN,Zoot,"Shoes,Clothing,Women's Shoes,All Women's Shoes","Blue,Multicolor",NaN,2016-11-11T09:49:00Z,2016-11-11T09:49:00Z,"[{""dateSeen"":[""2016-11-11T09:49:00Z""],""sourceU...",NaN,...,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN,"10,9",NaN,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN
3,AVpfBXx21cnluZ0-cKxs,NaN,Zoot,"Shoes,Clothing,Women's Shoes,All Women's Shoes","Blue,Multicolor",NaN,2016-11-11T09:49:00Z,2016-11-11T09:49:00Z,"[{""dateSeen"":[""2016-11-11T09:49:00Z""],""sourceU...",NaN,...,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN,"10,9",NaN,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN
4,AVpfEqFRLJeJML431x7w,NaN,Wild Pair,"Shoes,Women's Shoes,Clothing,All Women's Shoes",Brown,NaN,2016-11-16T12:56:36Z,2016-11-16T12:56:36Z,"[{""dateSeen"":[""2016-11-16T12:56:36Z""],""sourceU...",NaN,...,https://www.walmart.com/ip/Wild-Pair-Colfax-Wo...,NaN,NaN,NaN,"8.5,7,7.5,8",NaN,https://www.walmart.com/ip/Wild-Pair-Colfax-Wo...,7.63181E+11,NaN,NaN

In [19]:
man_shoe_df["categories"]

0                                                      Men
1                                                      Men
2                                                      Men
3                                                      Men
4           Shoes,Women's Shoes,Clothing,All Women's Shoes
                               ...
19040    Watches,Clothing, Shoes & Jewelry,Women,Wrist ...
19041                                                  Men
19042                                                  Men
19043                                                  Men
19044                                                  Men
Name: categories, Length: 19045, dtype: object

In [26]:
man_shoe_df['categories'] =man_shoe_df['categories'].replace(["Shoes,Clothing,Women's Shoes,All Women's Shoes"],"Men")
man_shoe_df['categories'] =man_shoe_df['categories'].replace(["Shoes,Women's Shoes,Clothing,All Women's Shoes"],"Men")
man_shoe_df['categories'] =man_shoe_df['categories'].replace(["Clothing,Shoes,Men's Shoes,All Men's Shoes"],"Men")

In [25]:
man_shoe_df.head(20)

,id,asins,brand,categories,colors,count,dateadded,dateupdated,descriptions,dimension,...,prices_sourceurls,prices_warranty,quantities,reviews,sizes,skus,sourceurls,upc,websiteids,weight
0,AVpfBXx21cnluZ0-cKxs,NaN,Zoot,Men,"Blue,Multicolor",NaN,2016-11-11T09:49:00Z,2016-11-11T09:49:00Z,"[{""dateSeen"":[""2016-11-11T09:49:00Z""],""sourceU...",NaN,...,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN,"10,9",NaN,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN
1,AVpfBXx21cnluZ0-cKxs,NaN,Zoot,Men,"Blue,Multicolor",NaN,2016-11-11T09:49:00Z,2016-11-11T09:49:00Z,"[{""dateSeen"":[""2016-11-11T09:49:00Z""],""sourceU...",NaN,...,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN,"10,9",NaN,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN
2,AVpfBXx21cnluZ0-cKxs,NaN,Zoot,Men,"Blue,Multicolor",NaN,2016-11-11T09:49:00Z,2016-11-11T09:49:00Z,"[{""dateSeen"":[""2016-11-11T09:49:00Z""],""sourceU...",NaN,...,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN,"10,9",NaN,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN
3,AVpfBXx21cnluZ0-cKxs,NaN,Zoot,Men,"Blue,Multicolor",NaN,2016-11-11T09:49:00Z,2016-11-11T09:49:00Z,"[{""dateSeen"":[""2016-11-11T09:49:00Z""],""sourceU...",NaN,...,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN,"10,9",NaN,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN
4,AVpfEqFRLJeJML431x7w,NaN,Wild Pair,Men,Brown,NaN,2016-11-16T12:56:36Z,2016-11-16T12:56:36Z,"[{""dateSeen"":[""2016-11-16T12:56:36Z""],""sourceU...",NaN,...,https://www.walmart.com/ip/Wild-Pair-Colfax-Wo...,NaN,NaN,NaN,"8.5,7,7.5,8",NaN,https://www.walmart.com/ip/Wild-Pair-Colfax-Wo...,7.63181E+11,NaN,NaN
5,AVpfEqFRLJeJML431x7w,NaN,Wild Pair,Men,Brown,NaN,2016-11-16T12:56:36Z,2016-11-16T12:56:36Z,"[{""dateSeen"":[""2016-11-16T12:56:36Z""],""sourceU...",NaN,...,https://www.walmart.com/ip/Wild-Pair-Colfax-Wo...,NaN,NaN,NaN,"8.5,7,7.5,8",NaN,https://www.walmart.com/ip/Wild-Pair-Colfax-Wo...,7.63181E+11,NaN,NaN
6,AVpfEqFRLJeJML431x7w,NaN,Wild Pair,Men,Brown,NaN,2016-11-16T12:56:36Z,2016-11-16T12:56:36Z,"[{""dateSeen"":[""2016-11-16T12:56:36Z""],""sourceU...",NaN,...,https://www.walmart.com/ip/Wild-Pair-Colfax-Wo...,NaN,NaN,NaN,"8.5,7,7.5,8",NaN,https://www.walmart.com/ip/Wild-Pair-Colfax-Wo...,7.63181E+11,NaN,NaN
7,AVpfFCfi1cnluZ0-dcCZ,NaN,Sutton Studio,"Women's Suits & Sets,Women's Clothing,All Wome...",Pink,NaN,2016-01-02T03:16:24Z,2016-04-06T03:01:11Z,NaN,NaN,...,http://www.sears.com/content/pdp/products/pric...,NaN,NaN,NaN,8,"[{""sourceURLs"":[""http://www.sears.com/content/...",http://www.sears.com/content/pdp/products/pric...,NaN,NaN,NaN
8,AVpfFCfi1cnluZ0-dcCZ,NaN,Sutton Studio,"Women's Suits & Sets,Women's Clothing,All Wome...",Pink,NaN,2016-01-02T03:16:24Z,2016-04-06T03:01:11Z,NaN,NaN,...,http://www.sears.com/content/pdp/products/pric...,NaN,NaN,NaN,8,"[{""sourceURLs"":[""http://www.sears.com/content/...",http://www.sears.com/content/pdp/products/pric...,NaN,NaN,NaN
9,AVpfBZCAilAPnD_xTN_K,NaN,LaLeela.com,"Women's Clothing,All Women's Clothing,Clothing...",NaN,NaN,2016-03-11T09:11:01Z,2016-03-25T01:13:39Z,NaN,1 in x 1 in x 1 in,...,http://www.sears.com/content/pdp/products/pric...,NaN,NaN,NaN,NaN,"[{""sourceURLs"":[""http://www.sears.com/content/...",http://www.sears.com/content/pdp/products/pric...,NaN,NaN,NaN
10,AVpfBZCAilAPnD_xTN_K,NaN,LaLeela.com,"Women's Clothing,All Women's Clothing,Clothing...",NaN,NaN,2016-03-11T09:11:01Z,2016-03-25T01:13:39Z,NaN,1 in x 1 in x 1 in,...,http://www.sears.com/content/pdp/products/pric...,NaN,NaN,NaN,NaN,"[{""sourceURLs"":[""http://www.sears.com/content/...",http://www.sears.com/content/pdp/products/pric...,NaN,NaN,NaN
11,AVpfHscY1cnluZ0-eVb6,NaN,Reebok,"Shoes,Clothing,Women's Shoes,All Women's Shoes...",Pink Ribbon,NaN,2016-04-30T08:06:16Z,2016-06-21T12:44:07Z,"[{""dateSeen"":[""2016-06-21T12:44:07Z""],""sourceU...",NaN,...,http://www.walmart.com/ip/Reebok-Skyscape-Chas...,NaN,NaN,NaN,"5.5M,6.5M,7M,7.5M,8.5M,6M,11M,9M,10M,8M,9.5M,5...","[{""sourceURLs"":[""http://www.shoes.com/womens-r...",http://www.walmart.com/ip/Reebok-Skyscape-Chas...,NaN,NaN,NaN
12,AVpfHscY1cnluZ0-eVb6,NaN,Reebok,"Shoes,Clothing,Women's Shoes,All Women's Shoes...",Pink Ribbon,NaN,2016-04-30T08:06:16Z,2016-06-21T12:44:07Z,"[{""dateSeen"":[""2016-06-21T12:44:07Z""],""sourceU...",NaN,...,http://www.walmart.com/ip/Reebok-Skyscape-Chas...,NaN,NaN,NaN,"5.5M,6.5M,7M,7.5M,8.5M,6M,11M,9M,10M,8M,9.5M,5...","[{""sourceURLs"":[""http://www.shoes.com/womens-r...",http://www.walmart.com/ip/Reebok-Skyscape-Chas...,NaN,NaN,NaN
13,AVpfHscY1cnluZ0-eVb6,NaN,Reebok,"Shoes,Clothing,Women's Shoes,All Women's Shoes...",Pink Ribbon,NaN,2016-04-30T08:06:16Z,2016-06-21T12:44:07Z,"[{""dateSeen"":[""2016-06-21T12:44:07Z""],""sourceU...",NaN,...,http://www.walmart.com/ip/Reebok-Skyscape-Chas...,NaN,NaN,NaN,"5.5M,6.5M,7M,7.5M,8.5M,6M,11M,9M,10M,8M,9.5M,5...","[{""sourceURLs"":[""http://www.shoes.com/womens-r...",http://www.walmart.com/ip/Reebok-Skyscape-Chas...,NaN,NaN,NaN
14,AVpfHscY1cnluZ0-eVb6,NaN,Reebok,"Shoes,Clothing,Women's Shoes,All Women's Shoes...",Pink Ribbon,NaN,2016-04-30T08:06:16Z,2016-06-21T12:44:07Z,"[{""dateSeen"":[""2016-06-21T12:44:07Z""],""sourceU...",NaN,...,http://www.walmart.com/ip/Reebok-Skyscape-Chas...,NaN,NaN,NaN,"5.5M,6.5M,7M,7.5M,8.5M,6M,11M,9M,10M,8M,9.5M,5...","[{""sourceURLs"":[""http://www.shoes.com/womens-r...",http://www.walmart.com/ip/Reebok-Skyscape-Chas...,NaN,NaN,NaN
15,AVpfHscY1cnluZ0-eVb6,NaN,Reebok,"Shoes,Clothing,Women's Shoes,All Women's Shoes...",Pink Ribbon,NaN,2016-04-30T08:06:16Z,2016-06-21T12:44:07Z,"[{""dateSeen"":[""2016-06-21T12:44:07Z""],""sourceU...",NaN,...,http://www.walmart.com/ip/Reebok-Skyscape-Chas...,NaN,NaN,NaN,"5.5M,6.5M,7M,7.5M,8.5M,6M,11M,9M,10M,8M,9.5M,5...","[{""sourceURLs"":[""http://www.shoes.com/womens-r...",http://www.walmart.com/ip/Reebok-Skyscape-Chas...,NaN,NaN,NaN
16,AVpfHscY1cnluZ0-eVb6,NaN,Reebok,"Shoes,Clothing,Women's Shoes,All Women's Shoes...",Pink Ribbon,NaN,2016-04-30T08:06:16Z,2016-06-21T12:44:07Z,"[{""dateSeen"":[""2016-06-21T12:44:07Z""],""sourceU...",NaN,...,http://www.shoes.com/womens-reebok-skyscape-ch...,NaN,NaN,NaN,"5.5M,6.5M,7M,7.5M,8.5M,6M,11M,9M,10M,8M,9.5M,5...","[{""sourceURLs"":[""http://www.shoes.com/womens-r...",http://www.walmart.com/ip/Reebok-Skyscape-Chas...,NaN,NaN,NaN
17,AVpfHscY1cnluZ0-eVb6,NaN,Reebok,"Shoes,Clothing,Women's Shoes,All Women's Shoes...",Pink Ribbon,NaN,2016-04-30T08:06:16Z,2016-06-21T12:44:07Z,"[{""dateSeen"":[""2016-06-21T12:44:07Z""],""sourceU...",NaN,...,http://www.shoes.com/womens-reebok-skyscape-ch...,NaN,NaN,NaN,"5.5M,6.5M,7M,7.5M,8.5M,6M,11M,9M,10M,8M,9.5M,5...","[{""sourceURLs"":[""http://www.shoes.com/womens-r...",http://www.walmart.com/ip/Reebok-Skyscape-Chas...,NaN,NaN,NaN
18,AVpfHscY1cnluZ0-eVb6,NaN,Reebok,"Shoes,Clothing,Women's Shoes,All Women's Shoes...",Pink Ribbon,NaN,2016-04-30T08:06:16Z,2016-06-21T12:44:07Z,"[{""dateSeen"":[""2016-06-21T12:44:07Z""],""sourceU...",NaN,...,http://www.shoes.com/womens-reebok-skyscape-ch...,NaN,NaN,NaN,"5.5M,6.5M,7M,7.5M,8.5M,6M,11M,9M,10M,8M,9.5M,5...","[{""sourceURLs"":[""http://www.shoes.com/womens-r...",http://www.walmart.com/ip/Reebok-Skyscape-Chas...,NaN,NaN,NaN
19,AVpfEqlqilAPnD_xUWBW,NaN,Jessica Simpson,Men,Beige,NaN,2017-01-27T01:20:05Z,2017-01-27T01:20:05Z,"[{""dateSeen"":[""2017-01-27T01:20:05Z""],""sourceU...",NaN,...,https://www.walmart.com/ip/Jessica-Simpson-Cai...,NaN,NaN,NaN,7,NaN,https://www.walmart.com/ip/Jessica-Simpson-Cai...,8.86924E+11,NaN,NaN

In [9]:
man_shoe_df.replace("Shoes,Clothing,Women's Shoes,All Women's Shoes", "Men")
man_shoe_df

,id,asins,brand,categories,colors,count,dateadded,dateupdated,descriptions,dimension,...,prices_sourceurls,prices_warranty,quantities,reviews,sizes,skus,sourceurls,upc,websiteids,weight
0,AVpfBXx21cnluZ0-cKxs,NaN,Zoot,"Shoes,Clothing,Women's Shoes,All Women's Shoes","Blue,Multicolor",NaN,2016-11-11T09:49:00Z,2016-11-11T09:49:00Z,"[{""dateSeen"":[""2016-11-11T09:49:00Z""],""sourceU...",NaN,...,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN,"10,9",NaN,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN
1,AVpfBXx21cnluZ0-cKxs,NaN,Zoot,"Shoes,Clothing,Women's Shoes,All Women's Shoes","Blue,Multicolor",NaN,2016-11-11T09:49:00Z,2016-11-11T09:49:00Z,"[{""dateSeen"":[""2016-11-11T09:49:00Z""],""sourceU...",NaN,...,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN,"10,9",NaN,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN
2,AVpfBXx21cnluZ0-cKxs,NaN,Zoot,"Shoes,Clothing,Women's Shoes,All Women's Shoes","Blue,Multicolor",NaN,2016-11-11T09:49:00Z,2016-11-11T09:49:00Z,"[{""dateSeen"":[""2016-11-11T09:49:00Z""],""sourceU...",NaN,...,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN,"10,9",NaN,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN
3,AVpfBXx21cnluZ0-cKxs,NaN,Zoot,"Shoes,Clothing,Women's Shoes,All Women's Shoes","Blue,Multicolor",NaN,2016-11-11T09:49:00Z,2016-11-11T09:49:00Z,"[{""dateSeen"":[""2016-11-11T09:49:00Z""],""sourceU...",NaN,...,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN,"10,9",NaN,https://www.walmart.com/ip/Zoot-TT-TRAINER-2.0...,NaN,NaN,NaN
4,AVpfEqFRLJeJML431x7w,NaN,Wild Pair,"Shoes,Women's Shoes,Clothing,All Women's Shoes",Brown,NaN,2016-11-16T12:56:36Z,2016-11-16T12:56:36Z,"[{""dateSeen"":[""2016-11-16T12:56:36Z""],""sourceU...",NaN,...,https://www.walmart.com/ip/Wild-Pair-Colfax-Wo...,NaN,NaN,NaN,"8.5,7,7.5,8",NaN,https://www.walmart.com/ip/Wild-Pair-Colfax-Wo...,7.63181E+11,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19040,AVpe6e3f1cnluZ0-Zsk7,"B00THZJCTY,B01A9EKQS2",NIXON,"Watches,Clothing, Shoes & Jewelry,Women,Wrist ...",Black,NaN,2016-03-20T22:00:58Z,2016-04-06T05:01:24Z,NaN,NaN,...,http://www.ebay.com/itm/Nixon-Ultratide-Yellow...,NaN,NaN,"[{""date"":""2015-09-18T00:00:00Z"",""dateAdded"":""2...",45,"[{""sourceURLs"":[""http://www.ebay.com/itm/Nixon...",http://www.amazon.com/Nixon-Ultratide-Watch-ye...,NaN,NaN,NaN
19041,AVpfXLGG1cnluZ0-jY7B,NaN,Tundra,"Shoes,Clothing,Women's Shoes,All Women's Shoes",Black,NaN,2017-01-12T19:07:57Z,2017-01-12T19:07:57Z,"[{""dateSeen"":[""2017-01-12T19:07:57Z""],""sourceU...",NaN,...,https://www.walmart.com/ip/Tundra-Lacie-Women-...,NaN,NaN,NaN,5,NaN,https://www.walmart.com/ip/Tundra-Lacie-Women-...,619650000000.0,NaN,NaN
19042,AVpfXLGG1cnluZ0-jY7B,NaN,Tundra,"Shoes,Clothing,Women's Shoes,All Women's Shoes",Black,NaN,2017-01-12T19:07:57Z,2017-01-12T19:07:57Z,"[{""dateSeen"":[""2017-01-12T19:07:57Z""],""sourceU...",NaN,...,https://www.walmart.com/ip/Tundra-Lacie-Women-...,NaN,NaN,NaN,5,NaN,https://www.walmart.com/ip/Tundra-Lacie-Women-...,619650000000.0,NaN,NaN
19043,AVpfXLGG1cnluZ0-jY7B,NaN,Tundra,"Shoes,Clothing,Women's Shoes,All Women's Shoes",Black,NaN,2017-01-12T19:07:57Z,2017-01-12T19:07:57Z,"[{""dateSeen"":[""2017-01-12T19:07:57Z""],""sourceU...",NaN,...,https://www.walmart.com/ip/Tundra-Lacie-Women-...,NaN,NaN,NaN,5,NaN,https://www.walmart.com/ip/Tundra-Lacie-Women-...,619650000000.0,NaN,NaN
19044,AVpfXLGG1cnluZ0-jY7B,NaN,Tundra,"Shoes,Clothing,Women's Shoes,All Women's Shoes",Black,NaN,2017-01-12T19:07:57Z,2017-01-12T19:07:57Z,"[{""dateSeen"":[""2017-01-12T19:07:57Z""],""sourceU...",NaN,...,https://www.walmart.com/ip/Tundra-Lacie-Women-...,NaN,NaN,NaN,5,NaN,https://www.walmart.com/ip/Tundra-Lacie-Women-...,619650000000.0,NaN,NaN

In [10]:
clean_men_df = men_shoe_df.at[2:19388,'categories'] =  "Men"
clean_men_df

InvalidIndexError: slice(2, 19388, None)

In [4]:
women_shoe_file = "../Resources/7004_1.csv"
women_shoe_df = pd.read_csv(women_shoe_file)
women_shoe_df.head()

/var/folders/_3/fpx1kffx6n90zjt7rjys0h6r0000gn/T/ipykernel_16119/2078812204.py:2: DtypeWarning: Columns (39,45) have mixed types. Specify dtype option on import or set low_memory=False.
  women_shoe_df = pd.read_csv(women_shoe_file)

,id,asins,brand,categories,colors,count,dateadded,dateupdated,descriptions,dimension,...,prices_warranty,quantities,reviews,sizes,skus,sourceurls,upc,vin,websiteids,weight
0,AVpfHrJ6ilAPnD_xVXOI,NaN,Josmo,"Clothing,Shoes,Men's Shoes,All Men's Shoes",NaN,NaN,2016-11-07T00:45:12Z,2016-11-07T00:45:12Z,"[{""dateSeen"":[""2016-11-07T00:45:12Z""],""sourceU...",NaN,...,NaN,NaN,NaN,NaN,NaN,https://www.walmart.com/ip/Josmo-8190-Plain-In...,699302044036,NaN,NaN,NaN
1,AVpfHrJ6ilAPnD_xVXOI,NaN,Josmo,"Clothing,Shoes,Men's Shoes,All Men's Shoes",NaN,NaN,2016-11-07T00:45:12Z,2016-11-07T00:45:12Z,"[{""dateSeen"":[""2016-11-07T00:45:12Z""],""sourceU...",NaN,...,NaN,NaN,NaN,NaN,NaN,https://www.walmart.com/ip/Josmo-8190-Plain-In...,699302044036,NaN,NaN,NaN
2,AVpfHsWP1cnluZ0-eVZ7,NaN,SERVUS BY HONEYWELL,"All Men's Shoes,Shoes,Men's Shoes,Clothing",NaN,NaN,2016-06-14T04:29:57Z,2016-07-09T20:26:48Z,"[{""dateSeen"":[""2016-07-09T20:26:48Z""],""sourceU...",NaN,...,NaN,NaN,NaN,NaN,NaN,http://www.walmart.com/ip/Studs-Shoe-Large-Pr-...,NaN,NaN,NaN,NaN
3,AVpfHsWP1cnluZ0-eVZ7,NaN,SERVUS BY HONEYWELL,"All Men's Shoes,Shoes,Men's Shoes,Clothing",NaN,NaN,2016-06-14T04:29:57Z,2016-07-09T20:26:48Z,"[{""dateSeen"":[""2016-07-09T20:26:48Z""],""sourceU...",NaN,...,NaN,NaN,NaN,NaN,NaN,http://www.walmart.com/ip/Studs-Shoe-Large-Pr-...,NaN,NaN,NaN,NaN
4,AVpfHsWP1cnluZ0-eVZ7,NaN,SERVUS BY HONEYWELL,"All Men's Shoes,Shoes,Men's Shoes,Clothing",NaN,NaN,2016-06-14T04:29:57Z,2016-07-09T20:26:48Z,"[{""dateSeen"":[""2016-07-09T20:26:48Z""],""sourceU...",NaN,...,NaN,NaN,NaN,NaN,NaN,http://www.walmart.com/ip/Studs-Shoe-Large-Pr-...,NaN,NaN,NaN,NaN

### Transform men's shoes DataFrame

In [4]:
# Create a filtered dataframe from specific columns
men_shoe_cols = ["id", "brand", "categories", "prices_amountmin", "prices_amountmax"]
men_shoe_transformed = clean_men_df[men_shoe_cols].copy()

# Rename the column headers
men_shoe_transformed = men_shoe_transformed.rename(columns={"prices_amountmin": "($)prices_min",
                                                          "prices_amountmax": "($)prices_max"})

# Clean the data by dropping duplicates and setting the index
men_shoe_transformed.drop_duplicates("id", inplace=True)
men_shoe_transformed.set_index("id", inplace=True)

men_shoe_transformed.head()

,brand,categories,($)prices_min,($)prices_max
id,,,,
AVpfBXx21cnluZ0-cKxs,Zoot,"Shoes,Clothing,Women's Shoes,All Women's Shoes",71.99,71.99
AVpfEqFRLJeJML431x7w,Wild Pair,"Shoes,Women's Shoes,Clothing,All Women's Shoes",26.98,26.98
AVpfFCfi1cnluZ0-dcCZ,Sutton Studio,"Women's Suits & Sets,Women's Clothing,All Wome...",318,318
AVpfBZCAilAPnD_xTN_K,LaLeela.com,"Women's Clothing,All Women's Clothing,Clothing...",27.98,27.98
AVpfHscY1cnluZ0-eVb6,Reebok,"Shoes,Clothing,Women's Shoes,All Women's Shoes...",22.99,22.99

# Transform women's shoes DataFrame

In [5]:
# Create a filtered dataframe from specific columns
women_shoe_cols = ["id", "brand", "categories", "prices_amountmin", "prices_amountmax"]
women_shoe_transformed = women_shoe_df[women_shoe_cols].copy()

# Rename the column headers
women_shoe_transformed = women_shoe_transformed.rename(columns={"prices_amountmin": "($)prices_min",
                                                          "prices_amountmax": "($)prices_max"})

# Clean the data by dropping duplicates and setting the index
women_shoe_transformed.drop_duplicates("id", inplace=True)
women_shoe_transformed.set_index("id", inplace=True)

women_shoe_transformed.head()

,brand,categories,($)prices_min,($)prices_max
id,,,,
AVpfHrJ6ilAPnD_xVXOI,Josmo,"Clothing,Shoes,Men's Shoes,All Men's Shoes",39.89,39.89
AVpfHsWP1cnluZ0-eVZ7,SERVUS BY HONEYWELL,"All Men's Shoes,Shoes,Men's Shoes,Clothing",40.02,40.02
AVpfAwehilAPnD_xS_eB,NATIVE,"Men's Casual Shoes,Shoes,Men's Shoes,Clothing",45.00,45.00
AVpfFCHeilAPnD_xUeS0,MAUI AND SONS,"All Men's Shoes,Shoes,Men's Shoes,Clothing",9.99,9.99
AVpfHssKilAPnD_xVXu5,Hao-bo,"Clothing, Shoes, Accessories,Bags, Briefcases,...",37.99,37.99

### changing value of categories from  men's shoes DataFrame

In [15]:
clean_men_df = men_shoe_transformed.loc[:,'categories'] =  "Men"

In [16]:
clean_men_df

'Men'

In [ ]:
#Combining Languages that had names masked together as well as separated

# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Clothing,Shoes,Men's Shoes,All Men's Shoes"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Men's Casual Shoes,Shoes,Men's Shoes,Clothing"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Clothing, Shoes, Accessories,Bags, Briefcases,Men's Accessories"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Men's Halloween Costumes,Adult Halloween Costumes,Clothing, Shoes & Accessories,Halloween,Men,Costumes, Reenactment, Theater,All Costumes,Costumes,Party & Occasions"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Clothing, Shoes & Accessories,Men's Clothing,Underwear"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Clothing, Shoes & Accessories,Men's Clothing,Shorts,Sporting Goods,Boxing, Martial Arts & MMA"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Clothing, Shoes, Accessories,Men's Sunglasses"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "All Men's Clothing,Men's Clothing,Men's Outerwear,Clothing, Shoes & Jewelry,Clothing"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Sporting Goods,Team Sports,Basketball,Clothing, Shoes & Accessories,Shoes,Men"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Clothing, Shoes & Accessories,Men's Accessories,Backpacks, Bags & Briefcases"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Athletic,Men,Shoes,Shoes & Handbags"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Men's Boots,Shoes,Men's Shoes,Clothing"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "All Men's Shoes,Shoes,Men's Shoes,Clothing"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Men,Shoes,Oxfords & Derby Shoes,Wingtip"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Clothing,Jewellery,Cufflinks & Shirt Accessories,Tie Clips,Clothing, Shoes & Jewelry,Men,Jewelry,Religious,Tie Pins & Clips,Ties & Cummerbunds,Accessories,Bags & Accessories"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Sporting Goods,Team Sports,Soccer,Clothing, Shoes & Accessories,Shoes & Cleats,Men"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Shoes,Clothing, Shoes & Jewelry,Men,Shoes & Handbags"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Clothing, Shoes & Accessories,Men's Shoes,Athletic"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Clothing,Shoes,Men's Shoes,Men's Casual Shoes"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Men's Running Shoes,Running Shoes,Running Gear,Fitness & Exercise Equipment,Men's Shoes,Athletic & Running Shoes"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Clothing, Shoes & Accessories,Team Sports,Men,Soccer,Shoes & Cleats,Sporting Goods"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Luggage & Bags,Juniors Messenger Bags & Backpacks,Home,Backpacks & Bags,Travel Bags,Bags & Accessories,Men's Bags,Juniors Accessories,Office Supplies,School Supplies,Backpacks,Men's Accessories,Clothing, Shoes & Jewelry"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Clothing, Shoes & Accessories,Men's Shoes,Boots,See more Thorogood Mens Classics Brown Leather EH Safet..."
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "SLP,Finish Line Athletic Shoes,Men,Nike Sneakers,Shoes"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Workwear & Uniforms,Men's Workwear & Uniforms,Men's Coveralls,Clothing, Shoes & Jewelry,Clothing,Men's Clothing"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Clothing,Shoes,Men's Shoes,Men's Dress Shoes"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Men's Dress Shoes,Shoes,Men's Shoes,Clothing"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Clothing, Shoes, Accessories,Men's Sunglasses,Women's Sunglasses"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Clothing, Shoes & Accessories,Men's Shoes,Athletic,Men"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Men's Work Gloves,Power Tools,Safety Apparel,Women's Workwear & Uniforms,Safety & Shop Gear,Workwear & Uniforms,Hand Tools,Clothing,Tools,Men's Clothing,Office Supplies,Women's Clothing,Women's Work Gloves,Gloves,Women's Workwear Accessories,Clothing, Shoes & Jewelry,Men's Workwear & Uniforms,Men's Workwear Accessories,Office Safety & Security"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Shoes,Clothing, Shoes & Jewelry,Men,Athletic,Team Sports,Basketball"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Clothing, Shoes & Accessories,Men's Accessories,Backpacks, Bags & Briefcases"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "All Men's Clothing,Men's Clothing,Clothing, Shoes & Jewelry,Clothing"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "All Men's Clothing,Men's Clothing,Men's Socks,Clothing, Shoes & Jewelry,Men's Socks & Underwear,Clothing"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Clothing, Shoes & Accessories,Men's Shoes,Casual"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Men,Shoes,Finish Line Athletic Shoes"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Home Improvement,Work Safety Clothing and Equipment,Men's Work & Safety Shoes"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Men,Shoes,Boat Shoes"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Sunglasses,Clothing, Shoes, Accessories,Walmart Vision Centers,Health,Men's Sunglasses"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Home Improvement,Men's Work & Safety Shoes,Work Safety Clothing and Equipment"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "All Men's Clothing,Men's Clothing,Clothing, Shoes & Jewelry,Men's Jeans,Clothing"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Clothing, Shoes & Accessories,Men's Accessories,Sunglasses & Fashion Eyewear,Sunglasses,Women's Accessories"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Men's Activewear,All Men's Clothing,Men's Clothing,Clothing, Shoes & Jewelry,Clothing"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Clothing, Shoes & Accessories,Men's Shoes,Boots"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Clothing, Shoes & Accessories,Men's Accessories,Hats"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Men's Boots,Shoes,Clothing, Shoes & Jewelry,Men's Shoes,Men's Work Shoes & Boots"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Jewelry,Fashion Jewelry,Fashion Rings,Clothing, Shoes & Jewelry,Men's Jewelry,Men's Rings"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Clothing, Shoes & Jewelry,Clothing,Men's Clothing,Men's Socks & Underwear,Men's Socks,All Men's Clothing"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Loafers & Slip-Ons,Men,Shoes,Clothing, Shoes & Jewelry"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Men's Jewelry,Men's Rings,Rings,Clothing, Shoes & Jewelry,Jewelry"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Men%27s Jewelry,Anniversary Jewelry,Clothing, Shoes & Jewelry,Fashion Bracelets & Charms,Bracelets,Jewelry,Men%27s Bracelets,Fashion Jewelry,Men%27s Anniversary Jewelry"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Athletic & Running Shoes,Men's Shoes,Cross-Training Shoes"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Clothing, Shoes & Accessories,Men's Clothing,Athletic Apparel"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Men's Sleepwear,All Men's Clothing,Home,Men's Clothing,Clothing, Shoes & Jewelry,Bath Robes & Wraps,Personal Care,Bath,Clothing,Bed & Bath,Bath Towels & Rugs"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Football,Clothing, Shoes & Accessories,Team Sports,Men,Shoes & Cleats,Sporting Goods"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Clothing, Shoes & Accessories,Men's Shoes,Athletic,See more Nike Air Jordan Future Low Cool Grey Black Whi..."
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "All Men's Shoes,Men's Casual Shoes,Shoes,Men's Shoes,Clothing"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == "Men's Slippers,Shoes,Men's Shoes,Clothing"
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == ""
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == ""
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == ""
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == ""
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == ""
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == ""
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == ""
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == ""
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == ""
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == ""
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == ""
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == ""
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == ""
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == ""
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == ""
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == ""
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == ""
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == ""
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == ""
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == ""
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == ""
# men_shoe_transformed.loc[men_shoe_transformed["categories"] == "Men's"] == ""

In [ ]:
complete_primary_home_language.loc[complete_primary_home_language["Language Name"] == "ADANGME", "Language Name"] = "ADANGME/AKAN/DAGOMBA/DAGBANE/FANTE/FANTI/GA/TWI/EWE/GURMA"

### changing value of categories from  women's shoes DataFrame

### Create database connection

In [ ]:
protocol = 'postgresql'
username = 'postgres'
password = '<password>'
host = 'localhost'
port = 5432
database_name = 'customer_db'
rds_connection_string = f'{protocol}://{username}:{password}@{host}:{port}/{database_name}'
engine = create_engine(rds_connection_string)

In [ ]:
# Confirm tables
inspector = inspect(engine)
inspector.get_table_names()

### Load DataFrames into database

In [ ]:
premise_transformed.to_sql(name='premise', con=engine, if_exists='append', index=True)

In [ ]:
county_transformed.to_sql(name='county', con=engine, if_exists='append', index=True)